# Generated by Django 4.2.11 on 2025-03-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='password',
        ),
    ]
