# Generated by Django 4.2.11 on 2025-03-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_room_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hash',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
