# Generated by Django 4.2.11 on 2025-03-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
